# Generated by Django 2.2.1 on 2019-05-17 10:26

import django.core.files.storage
from django.db import migrations, models
import modelformupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformupload', '0002_auto_20190517_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='document',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(), upload_to=modelformupload.models.get_upload_to),
        ),
    ]
